# Dictionary mapping social media platforms to their registration URLs
platform_registration_links = {
    "Facebook": "https://www.facebook.com/r.php",
    "Twitter": "https://twitter.com/i/flow/signup",
    "Instagram": "https://www.instagram.com/accounts/emailsignup/",
    "LinkedIn": "https://www.linkedin.com/signup/",
    "Pinterest": "https://www.pinterest.com/join/",
    "Snapchat": "https://accounts.snapchat.com/accounts/signup",
    "Reddit": "https://www.reddit.com/register/",
    "WhatsApp": "https://www.whatsapp.com/download",
    "Telegram": "https://telegram.org/",
    "WeChat": "https://www.wechat.com/en/",
    "Skype": "https://www.skype.com/en/get-skype/",
    "Discord": "https://discord.com/register",
    "Medium": "https://medium.com/m/signin?redirect=https%3A%2F%2Fmedium.com%2F",
    "Quora": "https://www.quora.com/",
    "Tumblr": "https://www.tumblr.com/",
    "YouTube": "https://www.youtube.com/",
    "Flickr": "https://www.flickr.com/signup",
    "Vimeo": "https://vimeo.com/join",
    "SoundCloud": "https://soundcloud.com/signin",
    "Mixcloud": "https://www.mixcloud.com/signup/",
    "LinkedIn": "https://www.linkedin.com/signup/",
    "Foursquare": "https://foursquare.com/signup",
    "DeviantArt": "https://www.deviantart.com/join/",
    "Behance": "https://www.behance.net/signup",
    "Dribbble": "https://dribbble.com/signup",
    "Pinterest": "https://www.pinterest.com/join/",
    "Snapchat": "https://accounts.snapchat.com/accounts/signup",
    "Foursquare": "https://foursquare.com/signup",
    "Reddit": "https://www.reddit.com/register/",
    "Product Hunt": "https://www.producthunt.com/",
    "Hacker News": "https://news.ycombinator.com/",
    "Minds": "https://www.minds.com/",
    "Gab": "https://gab.com/auth/sign_up",
    "VKontakte (VK)": "https://vk.com/join",
    "OK.ru": "https://ok.ru/",
    "Weibo": "https://weibo.com/signup/signup.php",
}