platform_search_links = {
    "Facebook": "https://www.facebook.com/search/top/?q=",
    "Twitter": "https://twitter.com/search?q=",
    "Instagram": "https://www.instagram.com/",
    "LinkedIn": "https://www.linkedin.com/search/results/all/?keywords=",
    "Pinterest": "https://www.pinterest.com/search/pins/?q=",
    "Snapchat": "https://accounts.snapchat.com/accounts/find_user",
    "Reddit": "https://www.reddit.com/user/",
    "Medium": "https://medium.com/search?q=",
    "Quora": "https://www.quora.com/search?q=",
    "Tumblr": "https://www.tumblr.com/search/",
    "YouTube": "https://www.youtube.com/results?search_query=",
    "Flickr": "https://www.flickr.com/search/?text=",
    "Vimeo": "https://vimeo.com/search?q=",
    "SoundCloud": "https://soundcloud.com/search?q=",
    "Mixcloud": "https://www.mixcloud.com/search/",
    "Foursquare": "https://foursquare.com/explore?q=",
    "DeviantArt": "https://www.deviantart.com/?q=",
    "Behance": "https://www.behance.net/?search=",
    "Dribbble": "https://dribbble.com/search?q=",
    "Product Hunt": "https://www.producthunt.com/search?q=",
    "Hacker News": "https://hn.algolia.com/?query=",
    "Minds": "https://www.minds.com/search?q=",
    "Gab": "https://gab.com/search?q=",
    "VKontakte (VK)": "https://vk.com/search/people?c[section]=people&c[q]=",
    "OK.ru": "https://ok.ru/search?st.mode=Users&st.grmode=Groups&st.postedByMembers=1&st.query=",
    "Weibo": "https://s.weibo.com/user?q=..."
}